### ISSUE TITLE
Flow condition fails

### ISSUE THREAD

**Issue by MrBlue90** [robertraaijmakers/com.trashchecker#94] opened 2020-06-25 18:47 UTC
Dear developers,

Since a few weeks ago, I started to notice that Homey doesn't remind me of putting out the trash.
While looking at the flows, they seem right to me, but fail nevertheless.

Looking at the app settings, I can't find anything odd, except for a number of "NaN" records.

Today, it's 25/6/2020 and also the debug log indicates that tomorrow, the "REST" trash needs to be picked up:
`{
  "GFT": [
    "03-01-2020",
    "17-01-2020",
    "31-01-2020",
    "14-02-2020",
    "28-02-2020",
    "13-03-2020",
    "27-03-2020",
    "10-04-2020",
    "24-04-2020",
    "08-05-2020",
    "22-05-2020",
    "05-06-2020",
    "19-06-2020",
    "03-07-2020",
    "17-07-2020",
    "31-07-2020",
    "14-08-2020",
    "28-08-2020",
    "11-09-2020",
    "25-09-2020",
    "09-10-2020",
    "23-10-2020",
    "06-11-2020",
    "20-11-2020",
    "04-12-2020",
    "18-12-2020",
    "2020-03-01",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "2020-10-04",
    "NaN-NaN-NaN",
    "2020-08-05",
    "NaN-NaN-NaN",
    "2020-05-06",
    "NaN-NaN-NaN",
    "2020-03-07",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "2020-11-09",
    "NaN-NaN-NaN",
    "2020-09-10",
    "NaN-NaN-NaN",
    "2020-06-11",
    "NaN-NaN-NaN",
    "2020-04-12",
    "NaN-NaN-NaN"
  ],
  "PMD": [
    "06-01-2020",
    "20-01-2020",
    "03-02-2020",
    "17-02-2020",
    "02-03-2020",
    "16-03-2020",
    "30-03-2020",
    "16-04-2020",
    "30-04-2020",
    "11-05-2020",
    "25-05-2020",
    "08-06-2020",
    "22-06-2020",
    "06-07-2020",
    "20-07-2020",
    "03-08-2020",
    "17-08-2020",
    "31-08-2020",
    "14-09-2020",
    "28-09-2020",
    "12-10-2020",
    "26-10-2020",
    "09-11-2020",
    "23-11-2020",
    "07-12-2020",
    "21-12-2020",
    "2020-06-01",
    "NaN-NaN-NaN",
    "2020-03-02",
    "NaN-NaN-NaN",
    "2020-02-03",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "2020-11-05",
    "NaN-NaN-NaN",
    "2020-08-06",
    "NaN-NaN-NaN",
    "2020-06-07",
    "NaN-NaN-NaN",
    "2020-03-08",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "2020-12-10",
    "NaN-NaN-NaN",
    "2020-09-11",
    "NaN-NaN-NaN",
    "2020-07-12",
    "NaN-NaN-NaN"
  ],
  "OVERIG": [
    "08-01-2020",
    "24-01-2020",
    "09-04-2020",
    "23-04-2020",
    "28-05-2020",
    "24-07-2020",
    "25-09-2020",
    "01-10-2020",
    "29-10-2020",
    "19-11-2020",
    "27-11-2020"
  ],
  "REST": [
    "10-01-2020",
    "07-02-2020",
    "06-03-2020",
    "03-04-2020",
    "01-05-2020",
    "29-05-2020",
    "26-06-2020",
    "24-07-2020",
    "21-08-2020",
    "18-09-2020",
    "16-10-2020",
    "13-11-2020",
    "11-12-2020",
    "2020-10-01",
    "2020-07-02",
    "2020-06-03",
    "2020-03-04",
    "2020-01-05",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "2020-11-12"
  ],
  "PAPIER": [
    "18-01-2020",
    "15-02-2020",
    "16-05-2020",
    "20-06-2020",
    "18-07-2020",
    "15-08-2020",
    "19-09-2020",
    "17-10-2020",
    "14-11-2020",
    "12-12-2020",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "NaN-NaN-NaN",
    "2020-12-12"
  ]
}`

Triggering this flow results in an error:
`IF 8PM, AND Tomorrow something will be picked up`, THEN send message`

Could anyone please support me in this?

Thanks,
Rick

**Comment by robertraaijmakers** [comment] 2020-07-27 07:53
Hi Rick,

Can you please provide which Trash API you are using? (and a sample postal code + house number to test with?).

Thanks!

**Comment by MrBlue90** [comment] 2020-08-24 21:55
Hi!
Apologies for the delay. Didn't noticed you reply until now.
I'm using the RD4 API.
Example: 6374BB 90
Thanks

**Comment by robertraaijmakers** [comment] 2020-09-15 09:42
Hi, sorry, same delay here.. I have checked the postal code and house number, but it seems that this doesn't give a response from the RD4 API at all?

If I check with 6374BA 159, it gives a valid response without any NaN values in between. I think this issue will be solved by some updates that have been done in between. Please wait till the next update and check if the issue is still there.

**Comment by MrBlue90** [comment] 2020-09-15 18:52
Hi Robert,
No worries.
I recently reinstalled the app and the NaN values dissappeared.
However, flows still didn't trigger even though trash was collected the day after.

**Comment by robertraaijmakers** [comment] 2020-09-16 06:34
Can you provide a screenshot of the flow? And are you sure the dates are correctly displayed in the debug section of the app?

**Comment by MrBlue90** [comment] 2020-09-27 19:13
Hi Robert,
Since there's a pickup planned tomorrow, I got to create a few screenshots for you.
As you can see, the debug info includes a PMD pickup for tomorrow, but the flow conditions fail for unknown reasons.
![image](https://user-images.githubusercontent.com/11852942/94373527-396fec80-0106-11eb-9f0d-a3c7064cb9df.jpeg)
![image](https://user-images.githubusercontent.com/11852942/94373537-44c31800-0106-11eb-893f-34fdc05ffcbe.png)

**Comment by robertraaijmakers** [comment] 2020-09-27 21:37
Sorry, just noticed this, should have seen it from the first log. The dates are in the wrong format (day, month, year) instead of year, month, day. This is why it fails only for the RD4 API... Just checked in a commit that should fix this. But you either have to install Homey 5.0 (beta), or wait for a little while. I upgraded the complete app to be compliant with the new App Developer Guidelines, but that does require an upgrade to Homey 5.0.

**Closed** 2020-09-27 21:38 UTC
Labels: fix-api

**Comment by MrBlue90** [comment] 2020-09-29 09:34
Thanks for the help Robert!
Given the current challenges with Homey v5.0 I'll wait for a little while.. 😄
