### ISSUE TITLE
No data 

### ISSUE THREAD

**Issue by Jovink** [robertraaijmakers/com.trashchecker#36] opened 2019-01-09 18:40 UTC

**Comment by Jovink** [comment] 2019-01-09 18:45
Hello, 
I use the Afvalkalender Meerlanden (zip code 2181VH. But there's no data anymore.
Only from 2018. Maybe they have changed the url? Can you please check it?
N.B. I am on Homey 2.0
`{
  "GFT": [
    "04-12-2018",
    "18-12-2018"
  ],
  "PAPIER": [
    "30-11-2018",
    "14-12-2018",
    "28-12-2018"
  ],
  "PLASTIC": [
    "23-11-2018",
    "07-12-2018",
    "21-12-2018"
  ],
  "REST": [
    "27-11-2018",
    "11-12-2018",
    "27-12-2018"
  ]
}
`

**Comment by robertraaijmakers** [comment] 2019-01-09 19:23
Duplicate of #34. Meerlanden changed it's API's and the API isn't working anymore.

**Closed by robertraaijmakers** 2019-01-09 19:23 UTC
