### ISSUE TITLE
global tag does not change from today to tomorrow

### ISSUE THREAD

**Issue by Raycokes2000** [robertraaijmakers/com.trashchecker#80] opened 2020-03-10 19:20 UTC
global tag does not change from todat to tomorrow
when changing for today to tomorrow it stil says today instead of displaying tomorow.
And save label button also does not acknowledge you have saved

**Comment by robertraaijmakers** [comment] 2020-03-10 23:07
Can you please try the new version that is just released to test? https://homey.app/a/com.trashchecker/test/

**Comment by Raycokes2000** [comment] 2020-03-12 00:27
nope, nothing changed the described behavior

**Comment by RobHomey** [comment] 2020-03-16 21:58
Robert, I face the same issue. When using the label: #Opgehaald in your flows, you get wrong information back. 
Example flow: "Afval wordt opgehaald: Morgen iets."
App setting: Ophaal type: Vandaag.(and save label)
Result: Vandaag wordt geen afval opgehaald.

Example flow: "Afval wordt opgehaald: Morgen iets."
App setting: Ophaal type: Morgen. (and save label).
Result: Morgen wordt Textiel opgehaald.

Conclusion:
When you select: Ophaal Type: Vandaag or Morgen and click on Save label, this makes the output of the flow change. I don't think it was meant to be.

**Comment by robertraaijmakers** [comment] 2020-03-17 06:37
Hi, this is exactly how it is meant to be.

Tomorrow means the label will show you which type is collected tomorrow. With this behavior you can make a flow run today (e.g. in the evening) to tell you which type of trash is collected tomorrow.

Today means the label will show you which type of trash is collected today. With this behavior you can make a flow that runs in the morning (e.g. when you come downstairs) to tell you which type of trash is collected today.

**Comment by RobHomey** [comment] 2020-03-17 07:08
I understand how it should work but it does not work like that. 
The app setting is overrouling  the flow. 

If you want to hear whether you have to put you trash out today or tomorrow, it is not going wel.
You cannot use “tomorrow” in a flow and in a 2nd flow “today” at the same time. 
This depends what you have selected in the app settings “Today/Tomorrow”

E.g. Lets say tomorrow is Plastic and I have 2 flows and selected in the app settings: “Today”
Result:
Flow Today: Nothings needs to put outside. 
Flow Tomorrow: Nothing needs to put outside. 

Select “Tomorrow” in the app settings. 
Result:
Flow Today: Nothing needs to put outside.
Flow Tomorrow: Put Plastic outside. 

That means on the day itself when Plastic needs to be collected you hear: Nothing needs to be put outside when you have selected Tomorrow in the app settings. 

I had the impression that it is possible to use “Today” and “Tomorrow” independently so that “Tomorrow” gives me the reminder and “Today” I have to put is outside. Unfortunately this is not the case right now.

**Comment by robertraaijmakers** [comment] 2020-03-17 07:19
I hope I understand you correctly and try to explain best how it should be used and how it was meant to be when the label was introduced.

The global tag is meant to be used as follows:
- When you have a flow that needs to notify you today then:
1. You use the check card "[any] trash is collected today"
2. In the trashcan app settings page you select "Today"
3. You use the global tag in an output (e.g. speech or push notification)

- When you have a flow that needs to notify you about trash being collected tomorrow then:
1. You use the check card "[any] trash is collected tomorrow"
2. In the trashcan app settings page you select "tomorrow"
3. You use the global tag in an output (e.g. speech or push notification)

The global tag label can't show different output based on a selected card in the flow. Therefor it is a **global** tag card and not a local tag card.

If you want to create 2 flows reminding you today **and** tomorrow. You should create this on your own with multiple flows and custom output strings (like it used to be before the global tag was introduced).

**Comment by robertraaijmakers** [comment] 2020-03-17 07:21
I probably start understanding what you mean. You say that when you select "tomorrow" in the settings, it acts as it is "today"?

**Comment by RobHomey** [comment] 2020-03-17 07:28
Yes that’s correct. Today overroules Tomorrow and the other way around. 
Maybe there is an easier way to explain maybe by phone why it is not working as aspected.

**Comment by robertraaijmakers** [comment] 2020-03-17 07:31
I simply cannot reproduce, I'm sorry.

When I select today (in my case) the global tag says:
"Nothing is collected today"

When I change to tomorrow, and save the app label settings the global tag says:
"The residual waste is collected tomorrow"

When I change to the day after tomorrow, and save the global tag says:
"The plastic is collected the day after tomorrow"

**Comment by robertraaijmakers** [comment] 2020-03-17 07:33
Stuur mij anders even een mail met je telefoonnummer, dan bel ik je even? dutchfighter@live.nl

**Comment by robertraaijmakers** [comment] 2020-03-17 07:54
To summarize the phone call:
- The label is updated correctly (as expected)
- However, the output from the flows is not as expected when using "tomorrow" in the "and" part of the flow

**Comment by RobHomey** [comment] 2020-03-17 07:59
Yes that’s correct.
Tomorrow I will check it again the output for the flow Today and the flow Tomorrow.

**Comment by RobHomey** [comment] 2020-03-17 09:01
I did some test and I can simulate the issue with one flow.

Today Textiel will be collected at my address.

I use in the flow the following card:


And for output:


In the app settings I have selected and saved:

Do not forget te select: Sla label op.

The output is ok and says: Rob, Vandaag wordt het Textiel opgehaald. Vergeet het niet buiten te zetten.
So far so good. 👍🏻

When you change in the app settings: Today to Tomorrow and Sla label op.

Then the output goes wrong.
You should expect for the today flow: Textiel buiten zetten but the output is: Morgen wordt er geen afval opgehaald.

This is what I meant with Vandaag iets is overruled by Ophaal type in the app settings.
I hope this will help you to identify the issue.

**Comment by robertraaijmakers** [comment] 2020-03-17 17:28
Ok, so this seems to be working as designed :)

How it works, scenario one:
- The settings page is set to " Today "
- The label will show " Today xxx is collected " OR " Today nothing is collected "
- The flow should contain (in the and column) the check " Trash will be collected Today Any "

Scenario two:
- The settings page is set to " Tomorrow "
- The label will show " Tomorrow xxx is collected " OR " Tomorrow nothing is collected "
- The flow should contain (in the and column) the check " Trash will be collected Tomorrow Any "

Scenario three:
- The settings page is set to " Day after tomorrow "
- The label will show " The day after tomorrow xxx is collected " OR " The day after tomorrow nothing is collected "
- The flow should contain (in the and column) the check " Trash will be collected Day after tomorrow Any "

These are the three supported scenarios.

If we take the following example, e.g. at my location:
- Today nothing is collected
- Tomorrow the plastic is collected
- The day after tomorrow the residual waste is collected

Then the behavior is as follows for the settings page (and the global label)
- If the settings page label is set to " Today " the global label will show : " Today nothing is collected "
- If the settings page label is set to " Tomorrow " the global label will show: " Tomorrow the plastic is collected "
- If the settings page label is set to " The day after tomorrow " the global label will show: " The day after tomorrow the residual waste is collected ".

The behaviour of the AND card will behave as follows
- If the card is " Trash will be collected Today ANY " it will result in FALSE and the flow is not executed
- If the card is " Trash will be collected Tomorrow ANY " it will result in TRUE and the flow is executed
- If the card is " Trash will be collected The day after tomorrow ANY " it will result in TRUE and the flow is executed.

If I take the example of @RobHomey with the one flow then (the flow contains the card " Trash will be collected TODAY ANY ") then
- When the settings page is set to TODAY ; The flow will execute and the label will say " Textiel wordt opgehaald " 
- When the settings page is set to TOMORROW ; the flow will execute and the label will say " Tomorrow nothing is collected "

This is BY DESIGN. The label is separate from the flow.

If I swith the flow of @RobHomey with the following (the flow contains the card " Trash will be collected TOMORROW ANY ") then:
- When the settings page is set to TODAY ; The flow WILL NOT execute (since no trash is collected tomorrow) BUT THE LABEL will still have " Textiel wordt opgehaald " (because the settings page says the label have to show the value for today)
- When the settings page is set to TOMORROW ; the flow WILL NOT execute (since no trash is collected tomorrow) and the label will have " Nothing is collected tomorrow "

So scenario 1A and 2B are the ones you need.

If you experience something else then described in the above scenario's please let me know (keep the format of the scenario's) and write down what you experience.

**Comment by RobHomey** [comment] 2020-03-18 08:58
Hi Robert,

Thanks for the mail,

It is clear to me that it is not possible right now to have more separate notifications for e.g. 2 or 3 days (Today, Tomorrow, Day before tomorrow).

What I was expecting is to have a notification the day before and on the day itself by creating to separate flows.
I wil delete the flow with the card Tomorrow for now and will only have a notification on the day itself (Today).

I hope in future updates that it will be possible to have separate multiple notifications (on the day itself and the day before) independed of the selection in the app settings.

Thanks for your support.

Kind regards,
Rob

**Comment by robertraaijmakers** [comment] 2020-03-18 19:22
Thanks for the feedback. Will see what I can do. But managing global labels in the app is not easily done. So I will close this issue since there is a work around.

If you want to achieve 2 messages, you can do 1 by using the global tag.
The other by creating 3 to 5 flows (one for each type) with a custom message.

**Closed by robertraaijmakers** 2020-03-18 19:22 UTC
Labels: wontfix

**Comment by robertraaijmakers** [comment] 2020-04-29 20:02
Potentieel toch een oplossing, in de nieuwe test versie zijn 3 labels beschikbaar (vandaag, morgen en overmorgen): https://homey.app/a/com.trashchecker/test/

**Comment by RobHomey** [comment] 2020-04-29 20:44
Hoi Robert,

Helemaal super ben de flows al aan het toevoegen om te testen. 

Groeten,
Rob

**Comment by RobHomey** [comment] 2020-04-29 21:02
Hoi Robert,

Ik heb de flows gemaakt en getest. Het werkt zonder problemen. Kan nu meldingen maken over afval dat morgen opgehaald wordt. 
Dank voor het toevoegen van deze optie. Vind het erg fijn dat deze nu beschikbaar is.

Groeten,
Rob
