### ISSUE TITLE
Please re-add RWM. New app RWM, no dates available in the Homey app.

### ISSUE THREAD

**Issue by RogerGorissen** [robertraaijmakers/com.trashchecker#198] opened 2024-08-02 18:17 UTC
A few weeks ago, RWM introduced a new app. Since then, the Homey trashchecker doesn't work anymore. 

Entering my zipcode and number in the settings of this app results in an error (address not available). So, the app has no dates available. At this moment I entered the dates on which the garbage is collected, myself.

Before RWM used mijnafvalwijzer.nl. Checking my data on that site also results in an error. So, seems like RWM has changed something.
I don't know what API RWM uses now.

I know there is a description of how to add a new collector myself. To do so, you have to know what API or website RWM uses. Besides, it's to difficult for me 😉.

So my question/ request: please re-add RWM to this app.

**Comment by robertraaijmakers** [comment] 2024-08-07 20:46
Duplicate of #197

**Closed by robertraaijmakers** 2024-08-07 20:46 UTC
Labels: duplicate, new-api
